services:
  ibrida:
    container_name: ibrida-noPond
    image: postgis/postgis:15-3.3
    shm_size: '16g'
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_SHARED_BUFFERS: 8GB
      POSTGRES_WORK_MEM: 2048MB
      POSTGRES_MAINTENANCE_WORK_MEM: 4GB
    volumes:
      - ~/repo/ibridaDB/dbTools:/tool
      - ~/repo/ibridaDB/dbQueries:/query
      - /peach/ibrida2:/var/lib/postgresql/data
      - /banana/miniH5/ibrida_exports:/exports
      - ../entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    ports:
      - "5432:5432"
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
