from sqlalchemy import create_engine, Column, Integer, String, Text, Boolean
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class TaxaExpanded(Base):
    __tablename__ = 'taxa_expanded'
    
    taxon_id = Column(Integer, primary_key=True, nullable=False)
    name = Column(String(64), index=True)
    common_name = Column(Text)
    rank = Column(Text)
    rank_level = Column(Integer, index=True)
    taxon_active = Column(Boolean, index=True)
    L5_taxon_id = Column(Integer)
    L5_name = Column(Text) # Ancestral string columns should be text
    L5_common_name = Column(Text) # In MySQL, this just stores a pointer to the string
    L10_taxon_id = Column(Integer) # This allows us to fit within the row width byte limit imposed by InnoDB
    L10_name = Column(Text)
    L10_common_name = Column(Text)
    L11_taxon_id = Column(Integer)
    L11_name = Column(Text)
    L11_common_name = Column(Text)
    L12_taxon_id = Column(Integer)
    L12_name = Column(Text)
    L12_common_name = Column(Text)
    L13_taxon_id = Column(Integer)
    L13_name = Column(Text)
    L13_common_name = Column(Text)
    L15_taxon_id = Column(Integer)
    L15_name = Column(Text)
    L15_common_name = Column(Text)
    L20_taxon_id = Column(Integer)
    L20_name = Column(Text)
    L20_common_name = Column(Text)
    L24_taxon_id = Column(Integer)
    L24_name = Column(Text)
    L24_common_name = Column(Text)
    L25_taxon_id = Column(Integer)
    L25_name = Column(Text)
    L25_common_name = Column(Text)
    L26_taxon_id = Column(Integer)
    L26_name = Column(Text)
    L26_common_name = Column(Text)
    L27_taxon_id = Column(Integer)
    L27_name = Column(Text)
    L27_common_name = Column(Text)
    L30_taxon_id = Column(Integer)
    L30_name = Column(Text)
    L30_common_name = Column(Text)
    L32_taxon_id = Column(Integer)
    L32_name = Column(Text)
    L32_common_name = Column(Text)
    L33_taxon_id = Column(Integer)
    L33_name = Column(Text)
    L33_common_name = Column(Text)
    L33_5_taxon_id = Column(Integer)
    L33_5_name = Column(Text)
    L33_5_common_name = Column(Text)
    L34_taxon_id = Column(Integer)
    L34_name = Column(Text)
    L34_common_name = Column(Text)
    L34_5_taxon_id = Column(Integer)
    L34_5_name = Column(Text)
    L34_5_common_name = Column(Text)
    L35_taxon_id = Column(Integer)
    L35_name = Column(Text)
    L35_common_name = Column(Text)
    L37_taxon_id = Column(Integer)
    L37_name = Column(Text)
    L37_common_name = Column(Text)
    L40_taxon_id = Column(Integer)
    L40_name = Column(Text)
    L40_common_name = Column(Text)
    L43_taxon_id = Column(Integer)
    L43_name = Column(Text)
    L43_common_name = Column(Text)
    L44_taxon_id = Column(Integer)
    L44_name = Column(Text)
    L44_common_name = Column(Text)
    L45_taxon_id = Column(Integer)
    L45_name = Column(Text)
    L45_common_name = Column(Text)
    L47_taxon_id = Column(Integer)
    L47_name = Column(Text)
    L47_common_name = Column(Text)
    L50_taxon_id = Column(Integer)
    L50_name = Column(Text)
    L50_common_name = Column(Text)
    L53_taxon_id = Column(Integer)
    L53_name = Column(Text)
    L53_common_name = Column(Text)
    L57_taxon_id = Column(Integer)
    L57_name = Column(Text)
    L57_common_name = Column(Text)
    L60_taxon_id = Column(Integer)
    L60_name = Column(Text)
    L60_common_name = Column(Text)
    L67_taxon_id = Column(Integer)
    L67_name = Column(Text)
    L67_common_name = Column(Text)
    L70_taxon_id = Column(Integer)
    L70_name = Column(Text)
    L70_common_name = Column(Text)
    L100_taxon_id = Column(Integer)
    L100_name = Column(Text)
    L100_common_name = Column(Text)